spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true
  h2:
    console:
      enabled: true

  redis:
    host: localhost
    port: 6379

# JWT 관련 설정
jwt.token:
  secret-key: PIC584tlILWtwxwTEK0RRogziyJWzGIbDFcaLLKnyC
  issuer: TEST
  audience: CUSTOMERS
